### ISSUE TITLE
Anti-cheat database problem

### ISSUE THREAD

**Issue by poryagholami** [TrinityCore/TrinityCoreCustomChanges#101]
**Description:**

There is a problem with the anti-cheat database
It is half installed

**Current behaviour:**

[Anticheatsql error.txt](https://github.com/TrinityCore/TrinityCoreCustomChanges/files/11105453/Anticheatsql.error.txt)

**Expected behaviour:**

It must be installed correctly

**Steps to reproduce the problem:**

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 60b75e3b6e81+ 2023-03-24 10:52:44 +0100 (3.3.5 branch) (Win64, Debug, Static) (authserver)

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** CHANGEME OS

**Comment by acidmanifesto** [comment]
What does this line say?
<https://github.com/TrinityCore/TrinityCoreCustomChanges/blob/b68e13e8180dfbdb7bb5e8979b2bb9a93911c5df/sql/character.anticheat.sql#L46>
