### ISSUE TITLE
Solocraft Crashes into the dungeon dungeon at level 25

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCoreCustomChanges#118]
**Description:**

Solocraft Crashes into the dungeon dungeon at level 25

**Current behavior:**

When I go into the Stormwind dungeon or other instances at level 25, Worldserver.exe crashes
always though If I use level 50 and go into the Stormwind dungeon, it doesn't crash. Switch
I Solocraft in the worldserver.conf from   Solocraft.Enable = 0   all instances work without
Problem when you are in the instance with level 50 there are strange characters in the chat it says
the level number.  --->  {}  or ({})    
 [SoloCraft] Admin entered {} - You have not been buffed. Your level is higher than the max Level ({ })

**Expected behavior:**

With Stormwind dungeons you can enter the instance from level 22 - 32 without it
Crashes with Solocraft

Example in the chat the characters must look like this

[SoloCraft] Admin entered {20} - You have not been buffed. Your level is higher than the max Level (40)

**Steps to reproduce the problem:**

https://www.wowhead.com/wotlk/zone=717/the-stockade

**Branch(s):**

3.3.5-solocraft

**TC rev. hash/commit:**

TrinityCore rev. 207432a0e9b9 2023-10-02 00:45:12 +0000 (3.3.5-solocraft branch) (Win64, RelWithDebInfo, Static)

**TDB version:**

World DB: TDB 335.23061

**Operating system:** CHANGEME OS

Windows 10

**Comment by acidmanifesto** [comment]
PR is put in. Thank you for the issue Report.
https://github.com/TrinityCore/TrinityCoreCustomChanges/pull/122
