### ISSUE TITLE
CrossFaction Battlegrounds not working as expected

### ISSUE THREAD

**Issue by stefan343** [TrinityCore/TrinityCoreCustomChanges#126]
**Description:**

When applying the latest .diff file in the core folder and starting the server, i notice strange behaviour. When logging in with 4 accounts (from the same IP and PC if it is needed to know) and joining a queue for battleground (whatever it is - WSG, AB, eye of the storm, and maybe even the others) i encounter some bugs.

**Current behaviour:**

First behaviour - When i click the button "Join Battle" with 4 of my accounts, and in DB the minimum required players are 2 for each faction, if they are all horde/alliance they need to be both 2/2 for it to begin (I don't know if it is a bug or it is just how the script works.).
Second behaviour - When entering with 2 alliance and 2 hordes, because it requires, it gives me a menu to join the battle, but when i do, all of my characters go in either Alliance spawn or in Horde spawn (It doesn't balance out both factions for them to be 2 in horde and 2 in alliance, if there are 4 players.) and it is kept like that even if i join with a 5th character - he joins in the spawn of where the other 4 characters are. 
Third behaviour - If the player is kicked for deserter, leaves the battleground, when he goes in the overworld, or the server restarts (for testing purposes) his name becomes "Unknown", but can still send messages, and in quite often occasions the player leaves the battleground with the race the BG gave to it. (I think the server keeps the data of the original race, because in the main menu it gives me the original race of the character, but when i join back in the server, it gives me a random race of the opposite faction every time i join the server with the specified character)

**Expected behaviour:**

Expected first behaviour *Maybe* - Join the battleground without requiring the minimum required players for both factions, rather require 4 players to queue to battleground. 
Expected second behaviour - For players to join BG in either alliance or horde faction and balance things out, not just only one of them (In some rare occasions one player joins the other team, but still 99% of the times all players join one side of the battleground.)
Expected third behaviour - When players leave the battleground (if they left, became afk, or if a server restart occurs) they get back their original race and name the player made his character instead of keeping the race the battleground gave to it.

**Steps to reproduce the problem:**

1. Step 1 - Join a battleground with 4 characters ( with the .diff script 2 alliance and 2 horde) *First behaviour* and see that the characters get in either horde or ally spawn if the first player that joins is horde or alliance. *Second behaviour*
2. Step 2 - Leave the battleground while being afk, with the button "Leave battleground" or restart the server and notice the player gets the name "Unknown" and if you wait 5 minutes for the BG to close. I have not been able to reproduce consistency with the player keeping his race the BG gave to it when it ends, but it occurs.

**Branch(es):**

3.3.5a

**TC rev. hash/commit:** 

TrinityCore rev. a787657557a9+ 2023-08-20 01:01:09 +0000 (master branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  TDB 335.23061

**Operating system:** Windows 10
![WoWScrnShot_112423_121427](https://github.com/TrinityCore/TrinityCoreCustomChanges/assets/41258060/187e9131-c05c-4a52-92b9-636b82b49267)

![WoWScrnShot_112423_122338](https://github.com/TrinityCore/TrinityCoreCustomChanges/assets/41258060/742216c6-38c3-4751-ae17-5456217e1737)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCoreCustomChanges/issues/64

**Comment by Aokromes** [comment]
patch is quite much abandoned.
