### ISSUE TITLE
Half of the TrinityCoreCustomChanges repositories didn't get updated

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCoreCustomChanges#135]
**Description:**

For some reason half of the [TrinityCoreCustomChanges](https://github.com/TrinityCore/TrinityCoreCustomChanges/branches/active) repositories didn't get updated from almost one month.

**Current behaviour:**

![Captură de ecran 2024-04-01 124343](https://github.com/TrinityCore/TrinityCoreCustomChanges/assets/24683355/dc04527d-be97-4c87-95ba-28ae522ef2c5)

**Expected behaviour:**

I guess they have to be updated like other half.

**Steps to reproduce the problem:**

1. Go to https://github.com/TrinityCore/TrinityCoreCustomChanges/branches/active
2. Notice

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

48c826061a74f70759af70eae3a7dc3f2e48a859

**TDB version:**  [TDB 335.24011](https://github.com/TrinityCore/TrinityCore/releases/tag/TDB335.24011)

**Operating system:** Windows11

**Comment by jackpoz** [comment]
https://github.com/jackpoz/TrinityCoreCron/actions is where the magic happens

**Comment by jackpoz** [comment]
Fixed

**Comment by CraftedRO** [comment]
@jackpoz looks like for some reason revision_data.h doesn't get updated, is this the expected behaviour ?

**Comment by jackpoz** [comment]
is that included in the GitHub repo at all or what do you mean ?

**Comment by CraftedRO** [comment]
I mean because [revision_data.h.in.cmake](https://github.com/TrinityCore/TrinityCoreCustomChanges/blob/3.3.5/revision_data.h.in.cmake) is not updated in TrinityCoreCustomChanges repositories aswell as it is in TC 3.3.5 main branch it will result that user won't be able to apply latest tdb release [TDB335.2404](https://github.com/TrinityCore/TrinityCore/releases/tag/TDB335.24041) with Updates.AutoSetup   = 1 in config.

**Comment by jackpoz** [comment]
that will get fixed after next sync

**Comment by CraftedRO** [comment]
seems like main issue still valid

**Comment by jackpoz** [comment]
this will happen whenever there are merge conflicts at https://github.com/jackpoz/TrinityCoreCron/actions . it's not "still valid", it's the same issue that happened again (and it will happen again and again)

**Comment by CraftedRO** [comment]
bump
