### ISSUE TITLE
[Crash] - Crash found in Wastelands

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCoreCustomChanges#136]
### Description

Something is crashing the server in the Wastelands
The crash occurs when you run past the NPC Outcast Necromancer (https://www.wowhead.com/classic/npc=11559/outcast-necromancer) in the Wasteland with GM turned on
[97d2fd54d55c+_worldserver.exe_[9-4_21-30-2].dmp](https://github.com/TrinityCore/TrinityCore/files/14927886/97d2fd54d55c%2B_worldserver.exe_.9-4_21-30-2.dmp)
[97d2fd54d55c+_worldserver.exe_[9-4_21-30-2].txt](https://github.com/TrinityCore/TrinityCore/files/14927888/97d2fd54d55c%2B_worldserver.exe_.9-4_21-30-2.txt)
[97d2fd54d55c+_worldserver.exe_[9-4_21-35-49].dmp](https://github.com/TrinityCore/TrinityCore/files/14927889/97d2fd54d55c%2B_worldserver.exe_.9-4_21-35-49.dmp)
[97d2fd54d55c+_worldserver.exe_[9-4_21-35-49].txt](https://github.com/TrinityCore/TrinityCore/files/14927890/97d2fd54d55c%2B_worldserver.exe_.9-4_21-35-49.txt)

### Expected behaviour

Stable operation

### Steps to reproduce the problem

Run to the GM past the NPC https://www.wowhead.com/classic/npc=11559/outcast-necromancer

### Branch

3.3.5

### TC rev. hash/commit

84220cb9a95c63e6dfd60028db8ad4b2d40c0db5

### Operating system

Win 2022

### Custom changes

[3.3.5-passive_anticheat](https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/3.3.5-passive_anticheat), [3.3.5-lfgsolo](https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/3.3.5-lfgsolo), [3.3.5-solocraft](https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/3.3.5-solocraft), [3.3.5-skip-dk](https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/3.3.5-skip-dk), Transmog from [Rochet2](https://github.com/Rochet2)

**Comment by jackpoz** [comment]
>	Parameter unsigned int mapId = 0x1
	Parameter float x = -2207.090088
	Parameter float y = 1593.839966
	Parameter float z = 61.736401

>std::string m_name = "Outcast Necromancer"

>G3D::Vector3 _startPosition
			float x = -2196.129883
			float y = 1602.550049
			float z = 60.188171
		G3D::Vector3 _endPosition
			float x = -2207.090088
			float y = 1593.839966
			float z = 60.236401

**Comment by jackpoz** [comment]
> ### Custom changes
> No

Are you sure you don't have any custom change at all ? Is LegendsWoWCore source code available on GitHub ?

**Comment by vahzxz** [comment]
> > ### Custom changes
> > No
> 
> Are you sure you don't have any custom change at all ? Is LegendsWoWCore source code available on GitHub ?

It's just that the emulator has been renamed and that's it. In fact, you can consider this a custom change

**Comment by vahzxz** [comment]
The crash occurs when you run past the NPC Outcast Necromancer (https://www.wowhead.com/classic/npc=11559/outcast-necromancer) in the Wasteland with GM turned on

> > Parameter unsigned int mapId = 0x1
> > Parameter float x = -2207.090088
> > Parameter float y = 1593.839966
> > Parameter float z = 61.736401
> 
> > std::string m_name = "Outcast Necromancer"
> 
> > G3D::Vector3 _startPosition
> > float x = -2196.129883
> > float y = 1602.550049
> > float z = 60.188171
> > G3D::Vector3 _endPosition
> > float x = -2207.090088
> > float y = 1593.839966
> > float z = 60.236401

The crash occurs when you run past the NPC Outcast Necromancer (https://www.wowhead.com/classic/npc=11559/outcast-necromancer) in the Wasteland with GM turned on

**Comment by CraftedRO** [comment]
84220cb9a95c63e6dfd60028db8ad4b2d40c0db5 well cannot reproduce it https://youtu.be/oxWNVDHBBkU are you sure you didn't modified your core with the code you posted in other ticket or smth else ?

**Comment by jackpoz** [comment]
When reporting an issue, it helps a lot if it's reproduced on a clean TC (as in, no C++ changes, no SQL database changes)

**Comment by vahzxz** [comment]
> [84220cb](https://github.com/TrinityCore/TrinityCore/commit/84220cb9a95c63e6dfd60028db8ad4b2d40c0db5) well cannot reproduce it https://youtu.be/oxWNVDHBBkU are you sure you didn't modified your core with the code you posted in other ticket or smth else ?

https://youtu.be/rLsbQEuSnLs

**Comment by vahzxz** [comment]
> [84220cb](https://github.com/TrinityCore/TrinityCore/commit/84220cb9a95c63e6dfd60028db8ad4b2d40c0db5) well cannot reproduce it https://youtu.be/oxWNVDHBBkU are you sure you didn't modified your core with the code you posted in other ticket or smth else ?

The crash happened even when I was just standing near the NPC and he was hitting me

**Comment by Shauren** [comment]
solocraft in chat...

no custom mods he says...

who knows what else is there

**Comment by CraftedRO** [comment]
> The crash happened even when I was just standing near the NPC and he was hitting me

How can npc hit you when you have .gm on (gm mode enable) ?

**Comment by vahzxz** [comment]
> solocraft in chat...
> 
> no custom mods he says...



> solocraft in chat...
> 
> no custom mods he says...
> 
> who knows what else is there

I thought it was required to specify user changes that could directly affect the cause of the crash. However, a patch made for solo dungeon crawling may affect this bug. If I'm wrong about something, then I apologize.

**Comment by vahzxz** [comment]
> > The crash happened even when I was just standing near the NPC and he was hitting me
> 
> How can npc hit you when you have .gm on (gm mode enable) ?

When I came in, there was no GMa, then I turned it on while I was leaving. The video shows the team.

**Comment by CraftedRO** [comment]
well you tried at least, next time write if ANY custom modification exist (even custom modifications from TrinityCoreCustomChanges repository), not just the ones created by you, maybe we need to edit issue template and describe more than it is already described :)

**Comment by vahzxz** [comment]
> well you tried at least, next time write if ANY custom modification exist (even custom modifications from TrinityCoreCustomChanges repository), not just the ones created by you, maybe we need to edit issue template and describe more than it is already described :)

Done

**Comment by CraftedRO** [comment]
wow you got something there it's still a miracle your server starts :frowning:

you can't expect "stable operation" with all of that changes, some of them are probably outdated and unmaintained from years.

**Comment by vahzxz** [comment]
> wow you got something there it's still a miracle your server starts 😦
> 
> you can't expect "stable operation" with all of that changes, some of them are probably outdated and unmaintained from years.

All changes were fixed with each update of Trinity

**Comment by vahzxz** [comment]
![image](https://github.com/TrinityCore/TrinityCore/assets/37352351/4f70d090-5079-4994-83e7-cf7f8826e785)
It's a pure core

**Comment by vahzxz** [comment]
> ![image](https://private-user-images.githubusercontent.com/37352351/321195818-4f70d090-5079-4994-83e7-cf7f8826e785.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDQ3NTgsIm5iZiI6MTcxMjc0NDQ1OCwicGF0aCI6Ii8zNzM1MjM1MS8zMjExOTU4MTgtNGY3MGQwOTAtNTA3OS00OTk0LTgzZTctY2Y3Zjg4MjZlNzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEwMjA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZmNjYTk1ZjNmNmZlNzEzNjg3ZTNjNTY1ZTMyODUzYWYzYzFiYmE3OWU2MWJhZDU1ZjhlZTc0ZDk0MWUzMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MNS9mJDmhhIqM3qe4yOyzPxC_dYpb1p4xp10pl9wpXw) It's a pure core

[84220cb9a95c_worldserver.exe_[10-4_13-19-40].dmp](https://github.com/TrinityCore/TrinityCore/files/14930890/84220cb9a95c_worldserver.exe_.10-4_13-19-40.dmp)
[84220cb9a95c_worldserver.exe_[10-4_13-19-40].txt](https://github.com/TrinityCore/TrinityCore/files/14930891/84220cb9a95c_worldserver.exe_.10-4_13-19-40.txt)

![image](https://github.com/TrinityCore/TrinityCoreCustomChanges/assets/37352351/f866058e-0f3f-4546-9f8f-e03ff06dab8c)
It is necessary to run up to this NPC in GM mode

**Comment by jackpoz** [comment]
Issue moved to TC custom changes.
I would suggest to try each branch on its own and spot which one crashes.

**Comment by vahzxz** [comment]
> Issue moved to TC custom changes.
> I would suggest to try each branch on its own and spot which one crashes.

So I turned on a clean core right now) Without any updates

**Comment by jackpoz** [comment]
![image](https://github.com/TrinityCore/TrinityCoreCustomChanges/assets/1153754/509653f5-adc0-4365-9683-7ed033fb7472)

do you have a custom client too ?

**Comment by vahzxz** [comment]
> ![image](https://private-user-images.githubusercontent.com/1153754/321197928-509653f5-adc0-4365-9683-7ed033fb7472.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDUxMzAsIm5iZiI6MTcxMjc0NDgzMCwicGF0aCI6Ii8xMTUzNzU0LzMyMTE5NzkyOC01MDk2NTNmNS1hZGMwLTQzNjUtOTY4My03ZWQwMzNmYjc0NzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMTAyNzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTc5MWExMTBmNTAwNTZkNDczMGRkN2Q5YTk1NTM5M2EwMzdlNWFmNWMyYTZkNTY5YzYwNWNmYzQwYWU1NzdmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zzeFjCHD6TuNs0FRlVhHwiEiGcfeYsrkCURMjfxu2zw)
> 
> do you have a custom client too ?

And how can the client influence the operation of the kernel?

**Comment by jackpoz** [comment]
If the client has bad map/vmap data, it will cause a crash when using that data, like in VMAP::VMapManager2::getHeight , which is where the crash is happening in this case.
Do you have custom map/vmap ? To be honest now I assume you have everything custom :P

**Comment by vahzxz** [comment]
> If the client has bad map/vmap data, it will cause a crash when using that data, like in VMAP::VMapManager2::getHeight , which is where the crash is happening in this case. Do you have custom map/vmap ? To be honest now I assume you have everything custom :P

The cards were collected from a clean client

**Comment by vahzxz** [comment]
The problem has been found.

**Comment by CraftedRO** [comment]
user error ?

**Comment by jackpoz** [comment]
@vahzxz what was the issue then ?

**Comment by vahzxz** [comment]
> @vahzxz what was the issue then ?

In a model that you will remember later)

**Comment by CraftedRO** [comment]
so it was a modded client issue ?

**Comment by vahzxz** [comment]
> so it was a modded client issue ?

No, I still say that the client cannot influence the Core, only thinks more stupidly about it. I say again that the cards were collected from a clean client. And this can't even happen with custom content, so that the server crumbles in the offline zone.....

**Comment by jackpoz** [comment]
did you spawn something in that location that is not spawned on clean TC ?
could it be "Flintspear01.m2" ?

**Comment by vahzxz** [comment]
> did you spawn something in that location that is not spawned on clean TC ? could it be "Flintspear01.m2" ?



> did you spawn something in that location that is not spawned on clean TC ? could it be "Flintspear01.m2" ?

I'm a moron, I decided to crash, but at the same time most of the created ones. I think that's how Trinity should be, when it should be ready for a lot of things....

**Comment by Shauren** [comment]
> > so it was a modded client issue ?
> 
> No, I still say that the client cannot influence the Core, only thinks more stupidly about it. I say again that the cards were collected from a clean client. And this can't even happen with custom content, so that the server crumbles in the offline zone.....

Oh it absolutely can - a modded map/model can be picked up by extractors, possibly corrupting maps/vmaps

**Comment by vahzxz** [comment]
> Oh it absolutely can - a modded map/model can be picked up by extractors, possibly corrupting maps/vmaps



> Oh it absolutely can - a modded map/model can be picked up by extractors, possibly corrupting maps/vmaps

Solved the problem of reassembling the cards

**Comment by vahzxz** [comment]
> > > so it was a modded client issue ?
> > 
> > 
> > No, I still say that the client cannot influence the Core, only thinks more stupidly about it. I say again that the cards were collected from a clean client. And this can't even happen with custom content, so that the server crumbles in the offline zone.....
> 
> Oh it absolutely can - a modded map/model can be picked up by extractors, possibly corrupting maps/vmaps

I never thought it was so important.

**Comment by vahzxz** [comment]
Anyway, thank you)
