### ISSUE TITLE
solo craft crashe on login game

### ISSUE THREAD

**Issue by ReyDonovan** [TrinityCore/TrinityCoreCustomChanges#139]
[f0635c0e4de0+_worldserver.exe_[31-7_19-34-50].dmp](https://github.com/user-attachments/files/16444800/f0635c0e4de0%2B_worldserver.exe_.31-7_19-34-50.dmp)
[f0635c0e4de0+_worldserver.exe_[31-7_19-34-50].txt](https://github.com/user-attachments/files/16444801/f0635c0e4de0%2B_worldserver.exe_.31-7_19-34-50.txt)

if mode off not problem
if mode on login on world game crashe

custom mode
reforge
transmog
lfg solo
anticheat
aoe loot
npc bot

last rev TC

**Comment by acidmanifesto** [comment]
Apply the sql to the character database
https://github.com/TrinityCore/TrinityCoreCustomChanges/blob/12b30b99f9b5f5c30a1779beacd96e5ddeb5d4df/sql/custom/characters/characters.solocraft.sql

**Comment by ReyDonovan** [comment]
![image](https://github.com/user-attachments/assets/17eb99ea-f661-41cd-9acb-94d20188f359)
no, that’s not the problem, the update to the patch was originally in the database

**Comment by kruchor** [comment]
Hello,

Please see issue #140
