### ISSUE TITLE
3.3.5-passive_anticheat Cannot apply diff on latest TC rev

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCoreCustomChanges#142]
**Description:**
After latest updates we're unable to use the diff thing.

https://github.com/TrinityCore/TrinityCoreCustomChanges/compare/3.3.5...3.3.5-passive_anticheat.diff can no longer be applied on latest TC 3.3.5 REV.da4312c58cbf405eda6aafeca5af2347c23b16cf

**Current behaviour:**

error: patch failed: src/server/game/Handlers/MovementHandler.cpp:358
error: src/server/game/Handlers/MovementHandler.cpp: patch does not apply

**Expected behaviour:**

No error

**Steps to reproduce the problem:**

1. Clone latest 3.3.5 source 
2. try to git bash the diff file from the above link
3. notice

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

da4312c58cbf405eda6aafeca5af2347c23b16cf

**TDB version:** TDB 335.24081

**Operating system:** Windows 11x64

**Comment by Aokromes** [comment]
known, branch needs resync

[18:56:18] <Aokromes>     WorldPacket data(opcode, recvData.size());
to
[18:56:18] <Aokromes>     WorldPacket data(opcode, recvPacket.size());

**Comment by CraftedRO** [comment]
Fixed by c9a6f54340f057ff362b6e55b89d48c6cc4c8847
