### ISSUE TITLE
[Anticheat] ‘teleport plane hack detection’ not  working properly

### ISSUE THREAD

**Issue by qxpf666** [TrinityCore/TrinityCoreCustomChanges#15]
players  can  still use teleport plane hack

**Comment by qxpf666** [comment]
Judgment can be corrected appropriately condition    

```
float x, y, z;
    player->GetPosition(x, y, z);
    float ground_Z = player->GetMap()->GetHeight(x, y, z);
    float z_diff = fabs(ground_Z - z);

    // we are not really walking there
    if (z_diff > 1.0f)
    {
        TC_LOG_DEBUG("entities.player.character", "AnticheatMgr:: Teleport To Plane - Hack detected player GUID (low) %u",player->GetGUID().GetCounter());
        BuildReport(player,TELEPORT_PLANE_HACK_REPORT);
    }
```

**Comment by Ovahlord** [comment]
Better use GetFloorZ() instead of GetHeight to use the cached Z value instead of doing a unnecessary vmap check.

**Comment by qxpf666** [comment]
maybe use GetPositionZ() - GetFloorZ()?

**Comment by Ovahlord** [comment]
sounds good to me.

**Comment by Aokromes** [comment]
test https://github.com/TrinityCore/TrinityCore/pull/23509 if it works better than passive anticheat it will be replaced by it.

**Comment by ghost** [comment]
@Aokromes It works. Of course, you can fool the check, but before that you will be marked 100 times in the logs.

**Comment by Khardoom** [comment]
Guys does the Anticheat detect The Hitchhiker's Hack [Fly, Wall, Teleport], because for me it doesn't?
Shows **0** for every action except Speed Hack which is detected correctly.

**Comment by yuyu-lovegelin111333** [comment]
Gents , Just tested in local server ,the Teleport detect and Walk on water both not working . 
Real hope someone can help to check how to use GetFloorZ() ?

**Comment by acidmanifesto** [comment]
https://github.com/TrinityCore/TrinityCoreCustomChanges/pull/73

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCoreCustomChanges/commit/d534d6ed0a2f883bff049f3ab28e9c47175a3307
