### ISSUE TITLE
add support solo mode in lfg

### ISSUE THREAD

**Issue by qyh214** [TrinityCore/TrinityCoreCustomChanges#20]
**Description:**

lfg system:we must have 5 players to play.

I think we can only one player use lfg system(we can set a npc do that),and press I you need to match queue keep the original function)

**Current behaviour:**
one player can not use lfg solo

**Expected behaviour:**

one player can use lfg solo

**Comment by LEO33SoFo** [comment]
I hope someone make this. **AzerothCore** already has this as a module.

**Comment by LEO33SoFo** [comment]
@qyh214 I converted this module from **AzerothCore**.
[Solo_lfg.patch](https://cdn.discordapp.com/attachments/291116559487991809/744825201597874176/Solo_lfg.patch)

Tested on https://github.com/TrinityCore/TrinityCore/commit/43986954fddc05e0fe1f225b0cf38a7b01f775bb.

**Comment by Aokromes** [comment]
> @qyh214 I converted this module from **AzerothCore**.
> [Solo_lfg.patch](https://cdn.discordapp.com/attachments/291116559487991809/744825201597874176/Solo_lfg.patch)
> 
> Tested on [TrinityCore/TrinityCore@4398695](https://github.com/TrinityCore/TrinityCore/commit/43986954fddc05e0fe1f225b0cf38a7b01f775bb).

plz make one pull request into https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/3.3.5-lfgsolo branch

**Comment by LEO33SoFo** [comment]
@Aokromes I just did it. Forgive me if I messed something up, this is my first time using online GIT, never knew what are concepts such FORK, PUSH, PULL, etc. :worried:

**Comment by qyh214** [comment]
I have test @LEO33SoFo  patch and all is well. thanks.
@Aokromes  maybe can do a pr?or @LEO33SoFo by yourself?

**Comment by Aokromes** [comment]
you can, to allow CIs to compile you only need to comment unused parameter.

**Comment by NoTitleGamesOfficial** [comment]
> @qyh214 I converted this module from **AzerothCore**. [Solo_lfg.patch](https://cdn.discordapp.com/attachments/291116559487991809/744825201597874176/Solo_lfg.patch)
> 
> Tested on [TrinityCore/TrinityCore@4398695](https://github.com/TrinityCore/TrinityCore/commit/43986954fddc05e0fe1f225b0cf38a7b01f775bb).

how can I use this?
