### ISSUE TITLE
New Autobalance for TrinityCore

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCoreCustomChanges#21]
https://github.com/aleigood/TrinityCore-Autobalance

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCoreCustomChanges/wiki

**Comment by nick25252525** [comment]
Does it also work with Shadowlands? How do I enter the autoba alance in Trinitycore?

**Comment by Aokromes** [comment]
no, it's 3.3.5a branch only.

**Comment by nick25252525** [comment]
Would it be possible to get that for Shadowlands?
