### ISSUE TITLE
flex raid difficulty from legion / bfa

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCoreCustomChanges#22]
maybe with one custom npc we can "queue" into a raid, the people will be send to 25m raid, with damage and health scaled and 10m mode loot.

https://wow.gamepedia.com/Flexible_Raid

**Comment by Aokromes** [comment]
maybe with this to start from LilleCarl.

we need now boss to increase hp and damage maybe amount of loot based on amount of players on map.

```
diff --git a/src/server/game/Maps/Map.cpp b/src/server/game/Maps/Map.cpp
index 38ea313087..c2dee87f1b 100644
--- a/src/server/game/Maps/Map.cpp
+++ b/src/server/game/Maps/Map.cpp
@@ -4234,7 +4234,7 @@ uint32 InstanceMap::GetMaxPlayers() const
 {
     MapDifficulty const* mapDiff = GetMapDifficulty();
     if (mapDiff && mapDiff->maxPlayers)
-        return mapDiff->maxPlayers;
+        return (mapDiff->maxPlayers == 10 ? 20 : mapDiff->maxPlayers);

     return GetEntry()->MaxPlayers;
 }

**Comment by Aokromes** [comment]
now with VAS patch maybe adding this to it will do the job.

**Comment by acidmanifesto** [comment]
I will see what I can do when i get home and will do a PR when i get it figured out

**Comment by acidmanifesto** [comment]
> now with VAS patch maybe adding this to it will do the job.

Travis CI tests all pass.

**Comment by Aokromes** [comment]
done with VAS.
