### ISSUE TITLE
support mail items in raid when bag is full

### ISSUE THREAD

**Issue by qyh214** [TrinityCore/TrinityCoreCustomChanges#27]
**Description:**
After CTM,we know that if in raid/dungeons, kill boss and loot,bag is full. after return home. you can receive mail with items from postmaster.

**Current behaviour:**

n/a

**Expected behaviour:**

like Description.

**Steps to reproduce the problem:**

1. kill boss in raid
2. bag is full and loot.
3.back to home.

**Branch(es):**

3.3.5

**Comment by ghost** [comment]
That would certainly be useful for normal players, since GM characters can open both .bank and .mailbox anywhere, or spawn a temp vendor.

**Comment by Aokromes** [comment]
it's one feature i wanted for long xd

**Comment by BertiRean** [comment]
I guess that is only for master branch right?

**Comment by Aokromes** [comment]
you missed the title of this repository.

**Comment by BertiRean** [comment]
Jajaja ok. I did one time a pre version, but don't considering the bag full. Just sending the items after corpse is removed.

**Comment by BertiRean** [comment]
Also, this feature is from the master. But the only difference in 3.3.5 will be the NPC source that sends the email. I did with the postmaster in a legion core.

**Comment by Aokromes** [comment]
that can be a setting xd

send allways or send when bags are full.

send quality

send value

**Comment by BertiRean** [comment]
In retail, you just send items from gear or quest items. But in legion, you need to ignore the AP tokens. The bag fulls is the same that send always. If you don't loot is because you don't have space or you forget to loot the mob.

**Comment by jackpoz** [comment]
should this be closed now that https://github.com/TrinityCore/TrinityCoreCustomChanges/pull/60 has been merged ?
