### ISSUE TITLE
Recreated Solocraft with Flexible Values per map with damage and spell scaling

### ISSUE THREAD

**Issue by acidmanifesto** [TrinityCore/TrinityCoreCustomChanges#32]
**Description:**

Recreated Solocraft with Flexible Values per map with damage and spell scaling.
I have a patch file for the lastest TC 335 ready for travis testing if there is interest in the branch.

**Current behavior:**

Scales both players health, and damage, and does individual adjustments inspired by my group's Flexcraft V2 module.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

Parent: 1ff4a7e75b56e1ad68d83f75b493a42ac1ae85c3 (DB/Quest: Fix CompletionText of 'The Balance of Nature')
Branch: 3.3.5
Follows: TDB335.64

**Comment by acidmanifesto** [comment]
Preview for the current World Server Conf That is actively being used with this build i have is here.
Did not want to spam with a huge wall of text.
https://pastebin.com/DtJAwnX9

**Comment by Aokromes** [comment]
make a PR vs 3.3.5-solocraft :)

**Comment by acidmanifesto** [comment]
will do in a hour or two when i get back home. thank you.

**Comment by acidmanifesto** [comment]
> make a PR vs 3.3.5-solocraft :)

All tests have passed.

**Comment by jackpoz** [comment]
Merged and added to the wiki at https://github.com/TrinityCore/TrinityCoreCustomChanges/wiki with description
>Solocraft with Flexible Values per map with damage and spell scaling to be able to solo dungeons/raids

Let me know if it should be changed.
