### ISSUE TITLE
Death Knight Starter Area Skip Module

### ISSUE THREAD

**Issue by acidmanifesto** [TrinityCore/TrinityCoreCustomChanges#36]
Description:

I have prepared a patch for a Death Knight Starter Area Skip Module based on my project's V2 Legion Consolidated Skip Module.

Current behavior:
Works for both horde and alliance new characters.
When Module is active (Conf = 1) and then a new character Death Knight is created, intro is played (not skippable). Character is then given flags and triggers based on quest completions for the starter areas and give the initial turn in quest after leaving the ebon hold. Alliance DK will be in storm wind with the quest https://www.wowhead.com/quest=13188/where-kings-walk ready for turn in, and Horde DK will be in Orgrimmar with the quest https://www.wowhead.com/quest=13189/saurfangs-blessing. All obtainable key Character Items are in the player's inventory or auto equipped, (Tabard, Weapons, Armors, and such). Spells such as Death Gate works and does return you to the appropriate ebon hold after the DK start zone chain quests are finished.
Tested and working on current 335 with all items and quests and triggers researched for 335 branch.

Preview Video: https://youtu.be/yBOx85LWly8

Branch(es):

3.3.5

TC rev. hash/commit:

Parent: 1ff4a7e (DB/Quest: Fix CompletionText of 'The Balance of Nature')
Branch: 3.3.5
Follows: TDB335.64

**Comment by Aokromes** [comment]
branch 3.3.5-skip-dk created

**Comment by acidmanifesto** [comment]
https://github.com/TrinityCore/TrinityCoreCustomChanges/pull/37
Merged
