### ISSUE TITLE
add﻿ to passive anticheat output of people being hac﻿king to chat windo﻿w

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCoreCustomChanges#4]
the current way makes messages to loss if you aren't looking to the screen on that exact moment

**Comment by Baynar** [comment]
Notify GM's in the Chat and no as a Notification might be better.

**Comment by Aokromes** [comment]
83c7294103b882b6b3e6ad4d9bec36a6b6723af2
