### ISSUE TITLE
lower weight for disenchant than greed

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCoreCustomChanges#41]
**Description:**

the idea is, think a raid with some people with 2nd spec, you don't "need" a item because it's not your main spec but you want to have it for 2nd spec, but then you find someone rolls disenchant and the roll is 100 and your is 99, and you find your precious item is destroyed.

**Current behaviour:**

greed and disenchant have same weight so 1-100 rolls of both rolls can lead people wanting a item to have it destroyed.

**Expected behaviour:**

disenchant have lower weight so 1-100 disenchant rolls never wins 1-100 greed rolls.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

f6e52f6b3df9

**Comment by Jinnaix** [comment]
No time to work on that at the moment, but writing down some thoughts on that:

While both rolls, greed and disenchant go into a greed roll pool, we still store if the roll is greed or disenchant.

```
        case ROLL_GREED:                                    // player choose Greed
            SendLootRoll(ObjectGuid::Empty, playerGUID, 128, ROLL_GREED, *roll);
            ++roll->totalGreed;
            itr->second = GREED;
            break;
        case ROLL_DISENCHANT:                               // player choose Disenchant
            SendLootRoll(ObjectGuid::Empty, playerGUID, 128, ROLL_DISENCHANT, *roll);
            ++roll->totalGreed;
            itr->second = DISENCHANT;
            break;
```

We could write an additional logic that compares the greed rolls depending on the selected outcome method and weight greed higher than disenchant with a factor of for example 5.
So if player 1 rolls 90 on greed, player 2 would need a disenchant roll of >= 95 to beat that.
A greed roll of 96 would always win against disenchant rolls and could only lose against a higher greed roll.

**Comment by Aokromes** [comment]
i was thinking if can be doable to limit disenchant rolls to 1-33 and greed ones to 34-100
on that way one disenchant never will win to one greed.

**Comment by Aokromes** [comment]
i was given:

```diff
diff --git a/src/server/game/Groups/Group.cpp b/src/server/game/Groups/Group.cpp
index 791960facd..b372fc439c 100644
--- a/src/server/game/Groups/Group.cpp
+++ b/src/server/game/Groups/Group.cpp
@@ -1537,7 +1537,17 @@ void Group::CountTheRoll(Rolls::iterator rollI, Map* allowedMap)
                     continue;
                 }
 
-                uint8 randomN = urand(1, 100);
+                uint8 min = 1;
+                uint8 max = 100;
+                if (itr->second == GREED)
+                {
+                    min = 34;
+                }
+                else
+                {
+                    max = 33;
+                }
+                uint8 randomN = urand(min, max);
                 SendLootRoll(ObjectGuid::Empty, itr->first, randomN, itr->second, *roll);
                 if (maxresul < randomN)
                 {

**Comment by Aokromes** [comment]
it looks to work properly:

[18:11:43] Disenchant Roll - 8 for [Raider's Cutlass of the Eagle] by Testaaw
[18:11:56] Greed Roll - 53 for [Vrykul Shackles] by Aokromes
[18:11:56] Disenchant Roll - 6 for [Vrykul Shackles] by Testaaw
[18:11:56] Aokromes won: [Vrykul Shackles]
[18:12:13] Aokromes has selected Disenchant for: [Oval Ring of the Gorilla]
[18:12:15] You have selected Greed for: [Oval Ring of the Gorilla]
[18:12:15] Disenchant Roll - 27 for [Oval Ring of the Gorilla] by Aokromes
[18:12:15] Greed Roll - 65 for [Oval Ring of the Gorilla] by Testaaw
[18:12:15] You won: [Oval Ring of the Gorilla]
