### ISSUE TITLE
1v1 Module

### ISSUE THREAD

**Issue by acidmanifesto** [TrinityCore/TrinityCoreCustomChanges#50]
**Description:**
I have a 1v1 Module that is completely module with no major core changes.
is this something you are interested in?

**Current behaviour:**
Conf and Specialization restrictions implemented.
Conf adjustable.
Cost to fight.
Completely module with no alterations of the core.

Targeted for current 335

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/1vs1 created
