### ISSUE TITLE
Solocraft parameters not taken into account (worldserver.conf)

### ISSUE THREAD

**Issue by kruchor** [TrinityCore/TrinityCoreCustomChanges#52]
**Description:**

When changing Solocraft parameters in worldserver.conf, nothing is taken into account

**Current behaviour:**

Changing any Solocraft parameter should be effective. 

**Expected behaviour:**

Default declared parameters value should be overriden by worldserver.conf values.

**Steps to reproduce the problem:**

1. Set Solocraft.Enable = 0 in worldserver.conf
2. Launch the game => Solocraft is still enabled
It sticks to default declared value "1" :

bool SoloCraftEnable = 1;

3. Set any other parameter (like Solocraft.Max.Level.Diff) in worldserver.conf, launch the game => nothing happened as expected

**Branch(es):**

TC> server debug
TC> TrinityCore rev. 243a8eb3c0bd+ 2021-08-02 03:33:51 +0000 (3.3.5-solocraft branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.67.0
Using MySQL version: 100329
Using CMake version: 3.13.4
Compiled on: Linux 5.4.128-1-pve
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8086
Realmlist (Realm Id: 1) configured in port 8086
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/wotlk/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/wotlk/data/vmaps. Total size: 1326890216 bytes
mmaps directory located in /home/wotlk/data/mmaps. Total size: 2019979420 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.21071
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

**TC rev. hash/commit:** 

trinity@wotlk:~/server-SC/bin$ ./worldserver
TrinityCore rev. 243a8eb3c0bd+ 2021-08-02 03:33:51 +0000 (3.3.5-solocraft branch) (Unix, RelWithDebInfo,                                         Static) (worldserver-daemon)

**TDB version:** 

Using World DB: TDB 335.21071

**Operating system:** 

trinity@wotlk:~/server-SC/bin$ cat /etc/debian_version
10.10

**Comment by acidmanifesto** [comment]
can you provide me some further clarification:
**Launch the game => Solocraft is still enabled
It sticks to default declared value "1"** 
What happens to tell you the module is still activated?
Also: 
**Set any other parameter (like Solocraft.Max.Level.Diff) in worldserver.conf, launch the game => nothing happened as expected**
What are the full settings used when using this?

**Comment by kruchor** [comment]
For instance, let's say I set 

trinity@wotlk:~/server-SC/etc$ grep Solocraft.Announce worldserver.conf
Solocraft.Announce = 0

![solocraft_announce](https://user-images.githubusercontent.com/71791764/129169266-646b8035-c34b-4880-ad41-4b91819b4ad2.png)

It is still announced to players.

Now default Max.Level.Diff is 10 :

trinity@wotlk:~/server-SC/etc$ grep Solocraft.Max.Level.Diff worldserver.conf
Solocraft.Max.Level.Diff = 10

My lvl 18 character is not buffed (wailing cavenrs) as my level is higher than the max level threshold . It should not be the case here.

![solocraft_leveldiff](https://user-images.githubusercontent.com/71791764/129169740-f0679ef7-1610-49ac-adbb-7e44a8e1e9d6.png)

Did I miss something ? Any other solocraft parameters are the default ones. I think the default declared parameters are used, whatever we change in worldserver.conf :

bool SoloCraftEnable = 1;
bool SoloCraftAnnounceModule = 1;
bool SoloCraftDebuffEnable = 1;
float SoloCraftSpellMult = 1.0;
float SoloCraftStatsMult = 100.0;
uint32 SolocraftLevelDiff = 1;
uint32 SolocraftDungeonLevel = 1;

For instance, If i recompile with _uint32 SolocraftLevelDiff = 10;_ the level threshold is then OK for a lvl 18 characters in wailing caverns.

**Comment by acidmanifesto** [comment]
> For instance, let's say I set
> 
> trinity@wotlk:~/server-SC/etc$ grep Solocraft.Announce worldserver.conf
> Solocraft.Announce = 0
> 
> ![solocraft_announce](https://user-images.githubusercontent.com/71791764/129169266-646b8035-c34b-4880-ad41-4b91819b4ad2.png)
> 
> It is still announced to players.
> 
> Now default Max.Level.Diff is 10 :
> 
> trinity@wotlk:~/server-SC/etc$ grep Solocraft.Max.Level.Diff worldserver.conf
> Solocraft.Max.Level.Diff = 10
> 
> My lvl 18 character is not buffed (wailing cavenrs) as my level is higher than the max level threshold . It should not be the case here.
> 
> ![solocraft_leveldiff](https://user-images.githubusercontent.com/71791764/129169740-f0679ef7-1610-49ac-adbb-7e44a8e1e9d6.png)
> 
> Did I miss something ? Any other solocraft parameters are the default ones. I think the default declared parameters are used, whatever we change in worldserver.conf :
> 
> bool SoloCraftEnable = 1;
> bool SoloCraftAnnounceModule = 1;
> bool SoloCraftDebuffEnable = 1;
> float SoloCraftSpellMult = 1.0;
> float SoloCraftStatsMult = 100.0;
> uint32 SolocraftLevelDiff = 1;
> uint32 SolocraftDungeonLevel = 1;
> 
> For instance, If i recompile with _uint32 SolocraftLevelDiff = 10;_ the level threshold is then OK for a lvl 18 characters in wailing caverns.

Thank you for the follow up. Not certain what changed in tc for the module to be effected like this but i got some changes submitted for the code review. once everything is good i will ping a tc dev to merge it.

**Comment by acidmanifesto** [comment]
At current i took the PR out of draft and it awaits further review and merging by a TC Dev.
https://github.com/TrinityCore/TrinityCoreCustomChanges/pull/53/
Feel free to pull it manually if you can for the time being. Thank you again for the report and the additional information @kruchor

**Comment by kruchor** [comment]
I'm glad to help. Currently compiling TC core with your changes. I'll test as soon as I can !
Thx !

**Comment by kruchor** [comment]
Well, compilation went fine and everything seems to be working now.
Parameters in worldserver.conf are successfully applied !
Thx for your work.

**Comment by acidmanifesto** [comment]
> Well, compilation went fine and everything seems to be working now.
> Parameters in worldserver.conf are successfully applied !
> Thx for your work.

A tc dev point out a few things for me to improve upon and look at. So keep your eyes out the next few days to see the new changes.

**Comment by acidmanifesto** [comment]
@kruchor so apparrently a rewrite was not needed, i just had to change one line and everything started working again. I was over thinking it too much. but do feel free to try, althought you will see no difference between the previous rewrite and the now current pr

**Comment by acidmanifesto** [comment]
@kruchor the final revision of solocraft has been tested and merged. if you can please close the issue unless you have anymore issues.

**Comment by jackpoz** [comment]
Marking the issue as closed as a fix was merged. You can continue adding comments and ask to reopen it if the issue was not fixed
