### ISSUE TITLE
crossfaction bg

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCoreCustomChanges#6]
A lot of people uses this patch on small servers.

https://gist.github.com/Aokromes/fe5ce4d06f69e2ff5e62ddacdc4291c9

**Comment by qxpf666** [comment]
Good,Is it the latest version?

**Comment by Aokromes** [comment]
updated to latest changes

**Comment by Aokromes** [comment]
superseded by https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/3.3.5-cfbg
