### ISSUE TITLE
slow down notifications of anticheat

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCoreCustomChanges#67]
**Description:**

atm hacks notification spam to much https://i.imgur.com/bxL0evq.png

**Expected behaviour:**

reduce the amount of notifications to 1 / 5s or 1 / 10s or 1 / 15s maybe config?

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

77098375396a

**Operating system:** CHANGEME OS

debian 10 x64.

**Comment by acidmanifesto** [comment]
https://github.com/TrinityCore/TrinityCoreCustomChanges/pull/73

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCoreCustomChanges/commit/d534d6ed0a2f883bff049f3ab28e9c47175a3307
