### ISSUE TITLE
NPCBOTS-Can anyone upgrade it?

### ISSUE THREAD

**Issue by qxpf666** [TrinityCore/TrinityCoreCustomChanges#7]
This is the old version. Can anyone upgrade it?

[2016_04_20-New-NPCBots.zip](https://github.com/TrinityCore/TrinityCoreCustomChanges/files/2908359/2016_04_20-New-NPCBots.zip)

**Comment by jackpoz** [comment]
isn't there a newer version around already ? either on github or bitbucket ?

**Comment by qxpf666** [comment]
yes,there is not

**Comment by jackpoz** [comment]
isn't it the same as PlayerBot ?

**Comment by Aokromes** [comment]
no, playerbot is player characters being bots, this is full npcs being bots.

**Comment by Baynar** [comment]
Has this been confirmed to be stable ?
I used cmangos playerbot and its full of crashes, i might try to update this to latest rev but i need to know if it was stable at first.

**Comment by jackpoz** [comment]
With none maintaining it there are most likely bugs

**Comment by qxpf666** [comment]
It's relatively stable, and sometimes it crash.

**Comment by qyh214** [comment]
@jackpoz @Aokromes maybe this more newer version 
- https://github.com/lasyan3/TrinityCore-Single
- https://github.com/lasyan3/TrinityCore-Single/commit/910dd858bfbf9e494eb4416c407f2af5c12fa3f1

and some improve

**Comment by qyh214** [comment]
now I think https://github.com/trickerer/Trinity-Bots is cool and well.

you can use it.

**Comment by Aokromes** [comment]
i added that on wiki days ago, forgot to close this.
