### ISSUE TITLE
3.3.5-solocraft database wrong

### ISSUE THREAD

**Issue by qyh214** [TrinityCore/TrinityCoreCustomChanges#75]
**Description:**
3.3.5-solocraft database:
```sql
-- Dumping structure for table characters.custom_solocraft_character_stats
DROP TABLE IF EXISTS `custom_solocraft_character_stats`;
CREATE TABLE IF NOT EXISTS `custom_solocraft_character_stats` (
  `GUID` tinyint(3) unsigned NOT NULL,
  `Difficulty` float NOT NULL,
  `GroupSize` int(11) NOT NULL,
  `SpellPower` int(10) unsigned NOT NULL DEFAULT '0',
  `Stats` float NOT NULL DEFAULT '100',
  PRIMARY KEY (`GUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```
guid should use int!
**Current behaviour:**

use tinyint will cause over 255 guid character wrong!

**Expected behaviour:**

tinyint to int

**Steps to reproduce the problem:**

n/a

**Branch(es):**3.3.5-solocraft

**Comment by acidmanifesto** [comment]
Thank you for the issue report. I had some time to finaly get around to it and did a pr dealing with your solution and also updating the sql to mysql8 format from depreciated formatting.

**Comment by Aokromes** [comment]
fix merged.
