### ISSUE TITLE
[3.3.5-aoe-loot-mail-excess] fill max slots of emails when sending items

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCoreCustomChanges#76]
atm when you have excess items you get 1 email for each excess item, a good idea can be fill the 12 possible slots to send less emails (if there are less than 12 excess item send with 2,3-10,11 items.

**Comment by jackpoz** [comment]
Thank you for reporting this issue @Aokromes . A fix has been applied, please update your local checkout to the latest version to get the fix.
:trollface:
