### ISSUE TITLE
Track custom changes between branches

### ISSUE THREAD

**Issue by Baynar** [TrinityCore/TrinityCoreCustomChanges#8]
Create a way for people that are using TrinityCore 3.3.5 Base to track changes in order to merge a custom patch into their core.

Simply put if i to get the changes for the pvprank patch i would need to research the whole core and extract the changes only for the pvprank patchs atm.

I really like the idea to have custom changes into the 3,3,5 branch but having them hidden behind 9000 commits is quite harsh and also people that are intretested in these custom patches would most of the time want to merge 2-3 if not all patches into 1 and use them all on their server, so having a way to see or merge only the changes for the patch will be really usefull.

**Comment by Aokromes** [comment]
that's why https://github.com/TrinityCore/TrinityCoreCustomChanges/wiki exists, only base patch is mandatory to apply other patches, the other patches where made to allow people to apply only 2 patches (base patch + real custom patch)

**Comment by Baynar** [comment]
Oh i didn't notice wiki was different, tnx for telling me.

So people need base branch in order to be able to merge the custom patches correct ?
Is every change gonna be in a different diff to keep it tidy ?

https://github.com/TrinityCore/TrinityCore/tree/3.3.5
and
https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/3.3.5-base_patch
are the same and auto merged for changes ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCoreCustomChanges/wiki contains the list of branches with links to "compare" and "diff". For example this is the 3.3.5-custom_links row:
* [3.3.5-custom_link](https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/3.3.5-custom_links) [compare](https://github.com/TrinityCore/TrinityCoreCustomChanges/compare/3.3.5...3.3.5-custom_links) [diff](https://github.com/TrinityCore/TrinityCoreCustomChanges/compare/3.3.5...3.3.5-custom_links.diff) Adds support to links with colored names

Clicking on [compare](https://github.com/TrinityCore/TrinityCoreCustomChanges/compare/3.3.5...3.3.5-custom_links) will show the modified files and clicking on [diff](https://github.com/TrinityCore/TrinityCoreCustomChanges/compare/3.3.5...3.3.5-custom_links.diff) will show a patch version of the changes, updated automatically by GitHub whenever you open the page. That's cool!

https://github.com/TrinityCore/TrinityCore/tree/3.3.5 is merged weekly automatically using https://travis-ci.org/jackpoz/TrinityCoreCron/branches , for example last one is https://travis-ci.org/jackpoz/TrinityCoreCron/builds/503044373 .

The branch 3.3.5-base_patch is a special branch used as base branch for 3.3.5-passive_anticheat, 3.3.5-pvpranks and 3.3.5-tele_npc_3 . This was the way these patches have been maintained in the past years and the structure was kept to simplify the current transition.
If you want for example include 3.3.5-passive_anticheat, you have 2 choices:
- merge 3.3.5-passive_anticheat branch into your fork. This will include 3.3.5-base_patch changes already.
- apply 3.3.5-base_patch diff on 3.3.5 and then apply 3.3.5-passive_anticheat diff
I personally suggest the merge way (as I hate patches) but please let us know if the merging experience doesn't work that good, especially if merging more than 1 branch.
