### ISSUE TITLE
Skip DK Module Broken

### ISSUE THREAD

**Issue by danjohnso** [TrinityCore/TrinityCoreCustomChanges#82]
**Description:**

The Skip DK module has a couple issues.  

If I enable the starter skip, I spawn in orgrimmar, but the quest turn in to Thrall is bugged.  The quest log seems to think it is "complete" and I have the quest item, but the dialogue with Thrall will not advance.

<img width="1805" alt="skip-dk-bug" src="https://user-images.githubusercontent.com/852995/176288645-c16aec24-78d6-443e-97ee-ed23908dd0b0.png">

If I disable the starter skip and try to use the dialogue with Lich King, nothing happens. 

**Steps to reproduce the problem:**

1. Enable DK skip module  
2. Create new Death knight
3. Login to character
4a. Run to Thrall, try to turn in quest
4b. Talk to Lich King, select "I wish to skip the Death Knight starter Questline"

**Branch(es):**
3.3.5a

**TC rev. hash/commit:** 
b9450bcdd0924ca69b5b2cc675f5c2b558ff9b47

TrinityCore rev. b9450bcdd092+ 2022-06-26 21:48:41 +0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.22061

**Operating system:** Ubuntu 21.10

**Comment by danjohnso** [comment]
Adding more info from testing.  
I never get the confirmation gossip menu from lich king when I say I want to skip the starting area using the optional mode.
Using GM commands, I was able to run .quest add 13189 and complete the quest with Thrall after abandoning the one the module gave me

**Comment by acidmanifesto** [comment]
I will look into the issue now.

**Comment by acidmanifesto** [comment]
Upon using the module. I talked to thrall and see it as a turn in:
![image](https://user-images.githubusercontent.com/16887899/177005688-bdb59cff-a884-49e6-b19c-8e25fbbe2c51.png)
However....
When i click on the turn in on the quest i see this.
![image](https://user-images.githubusercontent.com/16887899/177005722-33b3c338-862b-40c9-81f1-73ffac2177fe.png)

Relogging does not help. 

So out come. 

**This issue is CONFIRMED.**

Not entirely sure when this became a issue but i will see about correcting it. Thank you for the report @danjohnso

**Comment by danjohnso** [comment]
Do you also see the issue with the talking to lich king optional mode?  Personally, I think that option is much more blizzard like for the module.

Another minor thing I noticed was some client desync with the automatic completion.  I only had 9 (?) talent points when I dropped into Orgrimmar, but upon spending a few, it updated to the 49 I was expecting.

**Comment by acidmanifesto** [comment]
> Do you also see the issue with the talking to lich king optional mode? Personally, I think that option is much more blizzard like for the module.

yes. that is also a new issue that didnt exsist before. i have a fixed developed now and will do a pr in a few minutes. currently doing the type up at the moment for the PR

**Comment by acidmanifesto** [comment]
@danjohnso at the moment the pr is up and is working on my end for both optional gossip and just auto completing the turn in quests for both factions. Feel free to test the changes or you can wait til the maintainers merge it 
https://github.com/TrinityCore/TrinityCoreCustomChanges/pull/83

**Comment by danjohnso** [comment]
> @danjohnso at the moment the pr is up and is working on my end for both optional gossip and just auto completing the turn in quests for both factions. Feel free to test the changes or you can wait til the maintainers merge it #83

The automatic update works well, saves me a trip to Thrall too :)

For some reason the "Yes" option does nothing and the "No" option behaves like I expected the "Yes" option too.  Mostly strange because if they were simply reversed, I would have expected the "Yes" option to close the dialogue.  Do you not see this behavior @acidmanifesto?

**Comment by acidmanifesto** [comment]
> > @danjohnso at the moment the pr is up and is working on my end for both optional gossip and just auto completing the turn in quests for both factions. Feel free to test the changes or you can wait til the maintainers merge it #83
> 
> The automatic update works well, saves me a trip to Thrall too :)
> 
> For some reason the "Yes" option does nothing and the "No" option behaves like I expected the "Yes" option too.  Mostly strange because if they were simply reversed, I would have expected the "Yes" option to close the dialogue.  Do you not see this behavior @acidmanifesto?
> 

I did not have the issue with yes and no being flipped around. Selecting no also closed out the gossip for me. 

Correction. I had it happen to me twice so far out of 8 tries with 8 total new dks. its a bit weird. but if need be you can commit out the 
```
               // AddGossipItemFor(player, GOSSIP_ICON_INTERACT_1, "No", GOSSIP_SENDER_MAIN, NOSKIPDK);
```
that will remove the No option and you can just have the user click X or good bye or walk away from the npc to disregard the option

**Comment by danjohnso** [comment]
> > > @danjohnso at the moment the pr is up and is working on my end for both optional gossip and just auto completing the turn in quests for both factions. Feel free to test the changes or you can wait til the maintainers merge it #83
> > 
> > 
> > The automatic update works well, saves me a trip to Thrall too :)
> > For some reason the "Yes" option does nothing and the "No" option behaves like I expected the "Yes" option too.  Mostly strange because if they were simply reversed, I would have expected the "Yes" option to close the dialogue.  Do you not see this behavior @acidmanifesto?
> 
> I did not have the issue with yes and no being flipped around. Selecting no also closed out the gossip for me.
> 
> Correction. I had it happen to me twice so far out of 8 tries with 8 total new dks. its a bit weird. but if need be you can commit out the
> 
> ```
>                // AddGossipItemFor(player, GOSSIP_ICON_INTERACT_1, "No", GOSSIP_SENDER_MAIN, NOSKIPDK);
> ```
> 
> that will remove the No option and you can just have the user click X or good bye or walk away from the npc to disregard the option

Very strange.  It consistently happens for me across builds and operating systems.  I always get back 0 for the the Yes action and 1 for the No action.  I tried commenting that line out and it just got stuck in an infinite loop trying to talk to Lich King.  I think since there is only one option and it was 0, it just tried to auto complete that gossip option, hence the loop.  Ill try and look some more tomorrow, but it seems like the action int is not being sent/received with the gossip item and it is just defaulting to the order it was sent down.  

Haven't read a lot of Gossip Menu code yet, but I sort of assumed a new submenu would return a new menuId, but I get back 0 fro the menuId for both the initial conversation and the Yes/No confirmation, so that won't help this situation.

**Comment by acidmanifesto** [comment]
> > > > @danjohnso at the moment the pr is up and is working on my end for both optional gossip and just auto completing the turn in quests for both factions. Feel free to test the changes or you can wait til the maintainers merge it #83
> > > 
> > > 
> > > The automatic update works well, saves me a trip to Thrall too :)
> > > For some reason the "Yes" option does nothing and the "No" option behaves like I expected the "Yes" option too.  Mostly strange because if they were simply reversed, I would have expected the "Yes" option to close the dialogue.  Do you not see this behavior @acidmanifesto?
> > 
> > I did not have the issue with yes and no being flipped around. Selecting no also closed out the gossip for me.
> > 
> > Correction. I had it happen to me twice so far out of 8 tries with 8 total new dks. its a bit weird. but if need be you can commit out the
> > 
> > ```
> >                // AddGossipItemFor(player, GOSSIP_ICON_INTERACT_1, "No", GOSSIP_SENDER_MAIN, NOSKIPDK);
> > ```
> > 
> > that will remove the No option and you can just have the user click X or good bye or walk away from the npc to disregard the option
> 
> Very strange.  It consistently happens for me across builds and operating systems.  I always get back 0 for the the Yes action and 1 for the No action.  I tried commenting that line out and it just got stuck in an infinite loop trying to talk to Lich King.  I think since there is only one option and it was 0, it just tried to auto complete that gossip option, hence the loop.  Ill try and look some more tomorrow, but it seems like the action int is not being sent/received with the gossip item and it is just defaulting to the order it was sent down.  
> 
> Haven't read a lot of Gossip Menu code yet, but I sort of assumed a new submenu would return a new menuId, but I get back 0 fro the menuId for both the initial conversation and the Yes/No confirmation, so that won't help this situation.

Definately something odd going on. I will review a bit more in depth later.

**Comment by acidmanifesto** [comment]
@danjohnso https://github.com/TrinityCore/TrinityCoreCustomChanges/pull/84
