### ISSUE TITLE
3.3.5-vas-autobalance // it does not work autonomously

### ISSUE THREAD

**Issue by MrTajoli** [TrinityCore/TrinityCoreCustomChanges#91]
**Description:**

After downloading and compiling the "3.3.5-vas-autobalance" branch, autobalance seems to have a "_strange_" behavior:

if a player alone (not a gm) enters an instance, a message appears announcing that "autobalance" has detected the presence of 1 player on the map, but no changes are made to the health and damage of the mobs.

If you bring a gm to the player's position  in the same instance (.appear _player-name_) and the gm executes the command ".vas checkmaps", the mobs' health and damage values ​​are immediately changed. 

Is this the normal behavior?
If so, can this behavior be made automatic and without the need for GM's intervention? (players have no .vas commands).

**Branch(es):**

3.3.5-vas-autobalance

**Comment by Rochet2** [comment]
This should now have been fixed.
